### ISSUE TITLE
Why number of responses less than number of requests

### ISSUE THREAD

**Issue by Deleplace** [siadat/benchttp#2]
```
go run main.go -n 4 -c 1 http://localhost:8081
```

```
 Duration: 0.002s
 Requests: 2 (911.9/s)
   Errors: 0 (%0)
Responses: 1 (456.0/s)
    [200]: 2 (%200.0)
```

But, 1 != 2.
The server afaik did send a response for each request (unless some weird idempotence stuff is going on)

**Comment by siadat** [comment]
@Deleplace Thanks for reporting this issue. This should be fixed now. Could you please pull and retry on your server?

**Comment by siadat** [comment]
This is fixed, feel free to re-open if you see a problem again. Thanks!
